# Generated by Django 4.2.1 on 2024-04-29 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Category"
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Spouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
                ("m_count", models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Stars",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Minimum 1 characters"
                            ),
                            django.core.validators.MaxLengthValidator(
                                50, message="Maximum 50 characters"
                            ),
                        ],
                        verbose_name="Title",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                1, message="Minimum 1 characters"
                            ),
                            django.core.validators.MaxLengthValidator(
                                50, message="Maximum 50 characters"
                            ),
                        ],
                        verbose_name="Slug",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="photos/%Y/%m/%d/",
                        verbose_name="Photo",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="Article text")),
                (
                    "time_create",
                    models.DateTimeField(auto_now_add=True, verbose_name="Time create"),
                ),
                (
                    "time_update",
                    models.DateTimeField(auto_now=True, verbose_name="Update time"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        choices=[(False, "Draft"), (True, "Published")],
                        default=0,
                        verbose_name="Status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Star",
                "verbose_name_plural": "Stars",
                "ordering": ["-time_create"],
            },
        ),
        migrations.CreateModel(
            name="TagPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
    ]
