# Generated by Django 4.2.1 on 2024-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0002_alter_stars_options_stars_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stars",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
