# Generated by Django 4.2.1 on 2024-03-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0003_alter_stars_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stars",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
    ]
