# Generated by Django 4.2.1 on 2024-03-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0007_tagpost_alter_stars_cat_stars_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Spouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="stars",
            name="spouse",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="star",
                to="stars.spouse",
            ),
        ),
    ]
