# Generated by Django 4.2.1 on 2024-03-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0008_spouse_stars_spouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="spouse",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
