# Generated by Django 4.2.1 on 2024-04-07 20:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0009_spouse_m_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="stars",
            options={
                "ordering": ["-time_create"],
                "verbose_name": "Star",
                "verbose_name_plural": "Stars",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="Category"
            ),
        ),
        migrations.AlterField(
            model_name="stars",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="posts",
                to="stars.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="stars",
            name="content",
            field=models.TextField(blank=True, verbose_name="Article text"),
        ),
        migrations.AlterField(
            model_name="stars",
            name="is_published",
            field=models.BooleanField(
                choices=[(False, "Draft"), (True, "Published")],
                default=0,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="stars",
            name="slug",
            field=models.SlugField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Minimum 1 characters"
                    ),
                    django.core.validators.MaxLengthValidator(
                        50, message="Maximum 50 characters"
                    ),
                ],
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="stars",
            name="spouse",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="star",
                to="stars.spouse",
                verbose_name="Spouse",
            ),
        ),
        migrations.AlterField(
            model_name="stars",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="stars.tagpost", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="stars",
            name="time_create",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Time create"),
        ),
        migrations.AlterField(
            model_name="stars",
            name="time_update",
            field=models.DateTimeField(auto_now=True, verbose_name="Update time"),
        ),
        migrations.AlterField(
            model_name="stars",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, message="Minimum 1 characters"
                    ),
                    django.core.validators.MaxLengthValidator(
                        50, message="Maximum 50 characters"
                    ),
                ],
                verbose_name="Title",
            ),
        ),
    ]
