# Generated by Django 4.2.1 on 2024-04-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stars", "0010_uploadfiles_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stars",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Photo",
            ),
        ),
    ]
